### ISSUE TITLE
Exposed mongodb+srv credentials

### ISSUE THREAD

**Issue by eth0izzle** [mprasu23/me3d-POLL_APP#1]
**Potential security breach**. Verified credentials in URL `*redacted*:*redacted*@cluster0-mjqec.mongodb.net` in file [/config/db.js](https://github.com/mprasu23/me3d-POLL_APP/blob/master/config/db.js)<br/><br/>You should recycle your credentials immediately and move secrets to environment variables to prevent them being committed to GitHub.

**Comment by mprasu23** [comment]
This is taken care
